name: Front Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'ShiftMate_Front/**' # ShiftMate_Front 폴더에 변경사항이 있을 때만 실행
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/shiftmate-front
      FRONT_ENV_FILE: /home/ubuntu/shiftmate-front/.env

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./ShiftMate_Front # context 경로 지정
          file: ./ShiftMate_Front/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          platforms: linux/amd64

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          FRONT_ENV_FILE: ${{ env.FRONT_ENV_FILE }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          envs: IMAGE_NAME,FRONT_ENV_FILE
          script: |
            set -e
            # 서버 내 docker-compose.yml이 위치한 프로젝트 루트 폴더로 이동
            cd /home/ubuntu/ShiftMate

            # 최신 프론트엔드 이미지를 pull 받고 docker-compose로 재시작
            docker-compose pull frontend
            docker-compose up -d frontend
            
            # 사용하지 않는 도커 이미지 정리
            docker image prune -af
